### ISSUE TITLE
Latest release is almost 2 years old

### ISSUE THREAD

**Issue by darcato** [paulscherrerinstitute/StreamDevice#10]
I noticed that the latest release is almost 2 years old and the project has received some commits since. Should the latest commit be used or the latest release? Maybe it's time for a new release?

**Comment by darcato** [comment]
Thanks for the support, I see there are now new versions!

**Comment by dirk-zimoch** [comment]
I am working on 2-8 at the moment. It is not yet finished, thus it is on the development branch 2-8.
