### ISSUE TITLE
configure/RELEASE SUPPORT definition

### ISSUE THREAD

**Issue by keenanlang** [paulscherrerinstitute/StreamDevice#18]
synApps generally doesn't use full path names for referencing each module, instead defining module paths in reference to the macro SUPPORT. The use of the command 'make release' with StreamDevice ends up writing ASYN et al. as $(SUPPORT)/<module>-<tag>, but since configure/RELEASE doesn't have the SUPPORT macro, when trying to build, the modules aren't able to be found.

Even just adding "SUPPORT=" alongside the EPICS_BASE definition would be enough to get things to work with make release, even if you don't define it as anything or use said macro.

**Comment by dirk-zimoch** [comment]
I have now added SUPPORT= to configure/RELEASE

**Comment by keenanlang** [comment]
The line you added to the release file is "RELEASE=" not "SUPPORT="

**Comment by dirk-zimoch** [comment]
Oops. Fixed.
