### ISSUE TITLE
streamApp/Makefile issue

### ISSUE THREAD

**Issue by MarkRivers** [paulscherrerinstitute/StreamDevice#28]
streamApp/Makefile contains these lines:
```
# older calc versions require sscan
#PROD_LIBS += sscan
```
This is not correct.  Current versions of calc can still require sscan. If SSCAN is defined when calc is built then it includes swaitRecord.c, which requires sscan for recDynLink.

**Comment by dirk-zimoch** [comment]
I will change it to check if SSCAN is defined.

**Comment by dirk-zimoch** [comment]
Fixed in 7aa1802
