### ISSUE TITLE
testTimeStamp question

### ISSUE THREAD

**Issue by LeeHudsonDLS** [paulscherrerinstitute/StreamDevice#49]
Hi,
I'm trying to get the tests in this module working and i'm stuck on testTimeStamp. Can someone tell me anything about the "Epics" package that's required by this test? Is it a TCL package? If so do you know where I can get it from?

**Comment by dirk-zimoch** [comment]
It is a tcl package that we have at PSI. It is based on this: https://epics.anl.gov/EpicsDocumentation/ExtensionsManuals/TclTk/et.tcltk.html
As I wrote the tests for me, I did not spent any effort to make them run everywhere. Thea are from a time when this repo was not yet publicly available.

**Comment by dirk-zimoch** [comment]
See "caTCL" here: https://epics.anl.gov/extensions/tcl/index.php

**Comment by LeeHudsonDLS** [comment]
Ok thanks for the clarification
