### ISSUE TITLE
Potential out of bounds access of waveformRecord

### ISSUE THREAD

**Issue by mdavidsaver** [paulscherrerinstitute/StreamDevice#6]
This line was brought to my attention.  It, and the following loop, look like a guaranteed out of bounds access to BPTR.

https://github.com/paulscherrerinstitute/StreamDevice/blob/836388cd2295fcd359da70ffe8020687598157ec/src/devwaveformStream.c#L118

**Comment by dirk-zimoch** [comment]
At a first glance I would say off by 1.

Dirk

Am 08.12.2017 um 18:45 schrieb mdavidsaver <notifications@github.com<mailto:notifications@github.com>>:


This line was brought to my attention. It, and the following loop, look like a guaranteed out of bounds access to BPTR.

https://github.com/paulscherrerinstitute/StreamDevice/blob/836388cd2295fcd359da70ffe8020687598157ec/src/devwaveformStream.c#L118

**Comment by dirk-zimoch** [comment]
Fixed in commit 2a1f53a07affc50ecabc36beb9439d68f2158faa
