### ISSUE TITLE
An error occurred while installing StreamDevice

### ISSUE THREAD

**Issue by Lytt-2020** [paulscherrerinstitute/StreamDevice#72]
System: CentOS7--Linux
When installing StreamDevice, make an error when compiling:
/usr/bin/g++ -D_GNU_SOURCE -D_DEFAULT_SOURCE -D_X86_64_ -DUNIX -Dlinux -DUSE_TYPED_RSET -DSTREAM_INTERNAL -O3 -g -Wall -mtune=generic -m64 -fPIC -I. -I../O.Common -I. -I . -I.. -I../../include/compiler/gcc -I../../include/os/Linux -I../../include -I/home/lytt/local/epics /base/include/compiler/gcc -I/home/lytt/local/epics/base/include/os/Linux -I/home/lytt/local/epics/base/include -c ../AsynDriverInterface.cc
../AsynDriverInterface.cc:41:24: Fatal error: asynDriver.h: No such file or directory
  #include "asynDriver.h"
Excuse me, where is the problem? How to solve it? Please guide me! Thank you!

**Comment by Lytt-2020** [comment]
Hello! Thank you for your reply. I have installed "asyn", and I have set the installation path of the "asyn" module. I will paste the setting of "RELEASE" to the back and see if the format of the setting is correct. How to solve it? Thank you!
The contents of RELEASE are as follows:



TEMPLATE_TOP=$(EPICS_BASE)/templates/makeBaseApp/top


# If you don't want to install into $(TOP) then
# define INSTALL_LOCATION_APP here
#INSTALL_LOCATION_APP=<fullpathname&gt;


SUPPORT=$(TOP)/..
-include $(TOP)/../configure/SUPPORT.$(EPICS_HOST_ARCH)


ASYN=$(SUPPORT)/home/lytt/local/epics/asyn4-30
#CALC=$(SUPPORT)/calc-3-7
#PCRE=$(SUPPORT)/pcre-7-2


# EPICS_BASE usually appears last so other apps can override stuff:
EPICS_BASE=/home/lytt/local/epics/base


# These lines allow developers to override these RELEASE settings
# without having to modify this file directly.
-include $(TOP)/../RELEASE.local
-include $(TOP)/../RELEASE.$(EPICS_HOST_ARCH).local
-include $(TOP)/configure/RELEASE.local







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "paulscherrerinstitute/StreamDevice"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月31日(星期三) 晚上7:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [paulscherrerinstitute/StreamDevice] An error occurred while installing StreamDevice (#72)





 
I see no -I option with a path to the "asyn" module. Have you already built "asyn"?
 Have you set the ASYN variable in configure/RELEASE to the correct installation path of the "asyn" module?
 It seems you have set it to something, otherwise AsynDriverInterface.cc would not be built.

**Comment by dirk-zimoch** [comment]
After setting ASYN, have run run `make` in the top directory (or in configure)? Running `make` only in the src directory after changing the configuration is not sufficient. It is important that `make` runs in configure to set up the search path.

**Comment by Lytt-2020** [comment]
Thank you for your reply! I ran make in the top directory, but the same error still occurred, and I have configured my installation path. The file asynDreiver.h can be found in asyn. May I ask where the environment configuration is wrong? I put the configuration content of RELEASE at the end, you can take a look. Thank you!
Contents of RELEASE:
#RELEASE Location of external products
# Run "gnumake clean uninstall install" in the application
# top directory each time this file is changed.
#
# NOTE: The build does not check dependencies on files
# external to this application. Thus you should run
# "gnumake clean uninstall install" in the top directory
# each time EPICS_BASE, SNCSEQ, or any other external
# module defined in the RELEASE file is rebuilt.


TEMPLATE_TOP=$(EPICS_BASE)/templates/makeBaseApp/top


# If you don't want to install into $(TOP) then
# define INSTALL_LOCATION_APP here
#INSTALL_LOCATION_APP=<fullpathname&gt;


SUPPORT=$(TOP)/..
-include $(TOP)/../configure/SUPPORT.$(EPICS_HOST_ARCH)


ASYN=$(SUPPORT)/home/lytt/epics/asyn4/asyn4-38
#CALC=$(SUPPORT)/home/lytt/epics/calc/calc_R3-4/calc-3-4
PCRE=$(SUPPORT)/home/lytt/epics/streamdevice/StreamDevice-master/prce/prce2-10.36


# EPICS_BASE usually appears last so other apps can override stuff:
EPICS_BASE=/home/lytt/epics/base


# These lines allow developers to override these RELEASE settings
# without having to modify this file directly.
-include $(TOP)/../RELEASE.local
-include $(TOP)/../RELEASE.$(EPICS_HOST_ARCH).local
-include $(TOP)/configure/RELEASE.local





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "paulscherrerinstitute/StreamDevice"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月1日(星期四) 下午3:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [paulscherrerinstitute/StreamDevice] An error occurred while installing StreamDevice (#72)





 
After setting ASYN, have run run make in the top directory (or in configure)? Running make only in the src directory after changing the configuration is not sufficient. It is important that make runs in configure to set up the search path.

**Comment by dirk-zimoch** [comment]
Try to set ASYN to the absolute path:
`ASYN=/home/lytt/local/epics/asyn4-30`

**Comment by Lytt-2020** [comment]
Thank you for your reply! According to your statement, I tried again and it still didn't work. Excuse me, are other file environments not set correctly? Thank you!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "paulscherrerinstitute/StreamDevice"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月1日(星期四) 下午4:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [paulscherrerinstitute/StreamDevice] An error occurred while installing StreamDevice (#72)





 
Try to set ASYN to the absolute path:
 ASYN=/home/lytt/local/epics/asyn4-30

**Comment by dirk-zimoch** [comment]
Where are your components installed? Sometimes you use the path `/home/lytt/local/epics/asyn4-30` but sometimes `/home/lytt/epics/asyn4/asyn4-38`
ASYN should be set to the parent directory of the include and lib directories, where asyn has installed its files.
Where is asynDriver.h? If it is /home/lytt/local/epics/asyn4-30/include/asynDriver.h, then /home/lytt/local/epics/asyn4-30 is the correct value.

**Comment by Lytt-2020** [comment]
I'm very sorry, it took so long to get back to you! First of all thank you for your reply! Then the installation path of my component asyn is /home/lytt/epics/asyn4/asyn4-38. Among them, asyn4-38 contains include and lib directories. The path of my asynDriver.h is /asyn4-38/asyn/asynDriver/asynDriver.h, not in /include/asynDriver.h, is there something wrong with my file? I reinstalled it with CentOS7, but this problem still occurs. Is the version of asyn I use too high and incompatible with StreamDevice? Thank you very much for your attention!


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "paulscherrerinstitute/StreamDevice"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月1日(星期四) 下午4:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [paulscherrerinstitute/StreamDevice] An error occurred while installing StreamDevice (#72)





 
Where are your components installed? Sometimes you use the path /home/lytt/local/epics/asyn4-30 but sometimes /home/lytt/epics/asyn4/asyn4-38
 ASYN should be set to the parent directory of the include and lib directories, where asyn has installed its files.
 Where is asynDriver.h? If it is /home/lytt/local/epics/asyn4-30/include/asynDriver.h, then /home/lytt/local/epics/asyn4-30 is the correct value.

**Comment by dirk-zimoch** [comment]
Can it be that you have not yet built asyn? Go to your asyn4-38 and run make.

**Comment by Lytt-2020** [comment]
I have re-compiled asyn4-38 according to what you said, and there is no error. How can I tell that asyn has been installed successfully, can it be done without reporting an error? Thank you!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "paulscherrerinstitute/StreamDevice"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月1日(星期四) 晚上9:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [paulscherrerinstitute/StreamDevice] An error occurred while installing StreamDevice (#72)





 
Can it be that you have not yet built asyn? Go to your asyn4-38 and run make.

**Comment by dirk-zimoch** [comment]
Asyn should create directories `lib`, `include`, `dbd`  and a few others. If you have not set `INSTALL_LOCATION` it should have created those inside its own top location (asyn4-38). Do you find include/asynDriver.h there?

**Comment by Lytt-2020** [comment]
I can find include/asynDriver.h. But I can’t find INSTALL_LOCATION. If I want to create it, how do I need to create it? Thank you!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "paulscherrerinstitute/StreamDevice"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月1日(星期四) 晚上9:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [paulscherrerinstitute/StreamDevice] An error occurred while installing StreamDevice (#72)





 
Asyn should create directories lib, include, dbd  and a few others. If you have not set INSTALL_LOCATION it should have created those inside its own top location (asyn4-38). Do you find include/asynDriver.h there?

**Comment by dirk-zimoch** [comment]
Forget INSTALL_LOCATION. 
Set ASYN in StreamDevice to the parent directory of the include directory where asynDriver.h is and everything should work.

**Comment by Lytt-2020** [comment]
I’m very sorry to tell you, I recompiled it according to what you said, but it’s still not possible. The installation path of my include/asynDriver.h is /home/lytt/epics/asyn4/asyn4-38/include/asynDriver.h, so ASYN=/home/lytt/epics/asyn4/asyn4-38 or to /asyn4- 38/include still reports an error. May I ask if there is something that is not installed before the error is reported. Thank you!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "paulscherrerinstitute/StreamDevice"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月1日(星期四) 晚上10:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [paulscherrerinstitute/StreamDevice] An error occurred while installing StreamDevice (#72)





 
Forget INSTALL_LOCATION.
 Set ASYN in StreamDevice to the parent directory of the include directory where asynDriver.h is and everything should work.

**Comment by dirk-zimoch** [comment]
It should work like this.
Your StreamDevice installation is `/home/lytt/epics/streamdevice/StreamDevice-master`? (with for example `/home/lytt/epics/streamdevice/StreamDevice-master/src/StreamCore.cc`)
You configured ASYN in `/home/lytt/epics/streamdevice/StreamDevice-master/configure/RELEASE`?
Is there a directory `/home/lytt/epics/streamdevice/configure` ? That may be a problem.
What do you have in `/home/lytt/epics`? If you have `tree` installed, can you run `tree -d -L 3 -I 'O.*'` in `/home/lytt/epics` and mail the result to me?

**Comment by Lytt-2020** [comment]
The installation directory of my StreamDevice is /home/lytt/epics/streamdevice/StreamDevice-master, and it is just like the example you mentioned. I have configured the installation path of ASYN in RELEASE, and the path of configure is /home/lytt/epics/streamdevice/StreamDevice-master/configure. The tree in my epics is as follows. Thank you!


├── asyn4
│&nbsp; &nbsp;└── asyn4-38
│&nbsp; &nbsp; &nbsp; &nbsp;├── asyn
│&nbsp; &nbsp; &nbsp; &nbsp;├── bin
│&nbsp; &nbsp; &nbsp; &nbsp;├── configure
│&nbsp; &nbsp; &nbsp; &nbsp;├── db
│&nbsp; &nbsp; &nbsp; &nbsp;├── dbd
│&nbsp; &nbsp; &nbsp; &nbsp;├── documentation
│&nbsp; &nbsp; &nbsp; &nbsp;├── html
│&nbsp; &nbsp; &nbsp; &nbsp;├── include
│&nbsp; &nbsp; &nbsp; &nbsp;├── iocBoot
│&nbsp; &nbsp; &nbsp; &nbsp;├── lib
│&nbsp; &nbsp; &nbsp; &nbsp;├── makeSupport
│&nbsp; &nbsp; &nbsp; &nbsp;├── opi
│&nbsp; &nbsp; &nbsp; &nbsp;├── templates
│&nbsp; &nbsp; &nbsp; &nbsp;├── testApp
│&nbsp; &nbsp; &nbsp; &nbsp;├── testArrayRingBufferApp
│&nbsp; &nbsp; &nbsp; &nbsp;├── testAsynPortClientApp
│&nbsp; &nbsp; &nbsp; &nbsp;├── testAsynPortDriverApp
│&nbsp; &nbsp; &nbsp; &nbsp;├── testBroadcastApp
│&nbsp; &nbsp; &nbsp; &nbsp;├── testConnectApp
│&nbsp; &nbsp; &nbsp; &nbsp;├── testEpicsApp
│&nbsp; &nbsp; &nbsp; &nbsp;├── testErrorsApp
│&nbsp; &nbsp; &nbsp; &nbsp;├── testFtdiApp
│&nbsp; &nbsp; &nbsp; &nbsp;├── testGpibApp
│&nbsp; &nbsp; &nbsp; &nbsp;├── testGpibSerialApp
│&nbsp; &nbsp; &nbsp; &nbsp;├── testIPServerApp
│&nbsp; &nbsp; &nbsp; &nbsp;├── testManagerApp
│&nbsp; &nbsp; &nbsp; &nbsp;├── testOutputCallbackApp
│&nbsp; &nbsp; &nbsp; &nbsp;├── testOutputReadbackApp
│&nbsp; &nbsp; &nbsp; &nbsp;└── testUsbtmcApp
├── base
│&nbsp; &nbsp;├── bin
│&nbsp; &nbsp;│&nbsp; &nbsp;└── linux-x86_64
│&nbsp; &nbsp;├── configure
│&nbsp; &nbsp;│&nbsp; &nbsp;├── O.Common
│&nbsp; &nbsp;│&nbsp; &nbsp;├── O.linux-x86_64
│&nbsp; &nbsp;│&nbsp; &nbsp;└── os
│&nbsp; &nbsp;├── db
│&nbsp; &nbsp;├── dbd
│&nbsp; &nbsp;├── documentation
│&nbsp; &nbsp;├── html
│&nbsp; &nbsp;│&nbsp; &nbsp;├── freeList
│&nbsp; &nbsp;│&nbsp; &nbsp;├── gpHash
│&nbsp; &nbsp;│&nbsp; &nbsp;└── image
│&nbsp; &nbsp;├── include
│&nbsp; &nbsp;│&nbsp; &nbsp;├── compiler
│&nbsp; &nbsp;│&nbsp; &nbsp;└── os
│&nbsp; &nbsp;├── lib
│&nbsp; &nbsp;│&nbsp; &nbsp;├── linux-x86_64
│&nbsp; &nbsp;│&nbsp; &nbsp;├── perl
│&nbsp; &nbsp;│&nbsp; &nbsp;└── pkgconfig
│&nbsp; &nbsp;├── src
│&nbsp; &nbsp;│&nbsp; &nbsp;├── ca
│&nbsp; &nbsp;│&nbsp; &nbsp;├── ioc
│&nbsp; &nbsp;│&nbsp; &nbsp;├── libCom
│&nbsp; &nbsp;│&nbsp; &nbsp;├── std
│&nbsp; &nbsp;│&nbsp; &nbsp;├── template
│&nbsp; &nbsp;│&nbsp; &nbsp;└── tools
│&nbsp; &nbsp;├── startup
│&nbsp; &nbsp;├── templates
│&nbsp; &nbsp;│&nbsp; &nbsp;├── makeBaseApp
│&nbsp; &nbsp;│&nbsp; &nbsp;└── makeBaseExt
│&nbsp; &nbsp;└── top
│&nbsp; &nbsp; &nbsp; &nbsp;├── bin
│&nbsp; &nbsp; &nbsp; &nbsp;├── configure
│&nbsp; &nbsp; &nbsp; &nbsp;├── db
│&nbsp; &nbsp; &nbsp; &nbsp;├── dbd
│&nbsp; &nbsp; &nbsp; &nbsp;├── firstIocApp
│&nbsp; &nbsp; &nbsp; &nbsp;├── include
│&nbsp; &nbsp; &nbsp; &nbsp;├── iocBoot
│&nbsp; &nbsp; &nbsp; &nbsp;└── lib
├── calc
│&nbsp; &nbsp;└── calc_R3-4
│&nbsp; &nbsp; &nbsp; &nbsp;└── calc-3-4
├── extensions
│&nbsp; &nbsp;├── bin
│&nbsp; &nbsp;│&nbsp; &nbsp;└── linux-x86_64
│&nbsp; &nbsp;├── configure
│&nbsp; &nbsp;│&nbsp; &nbsp;├── O.Common
│&nbsp; &nbsp;│&nbsp; &nbsp;├── O.linux-x86_64
│&nbsp; &nbsp;│&nbsp; &nbsp;└── os
│&nbsp; &nbsp;├── lib
│&nbsp; &nbsp;│&nbsp; &nbsp;└── linux-x86_64
│&nbsp; &nbsp;└── src
│&nbsp; &nbsp; &nbsp; &nbsp;└── medm
├── ipac
│&nbsp; &nbsp;└── ipac-2.15
│&nbsp; &nbsp; &nbsp; &nbsp;├── configure
│&nbsp; &nbsp; &nbsp; &nbsp;├── drvIpac
│&nbsp; &nbsp; &nbsp; &nbsp;├── drvTip810
│&nbsp; &nbsp; &nbsp; &nbsp;├── iocsh
│&nbsp; &nbsp; &nbsp; &nbsp;├── ip520
│&nbsp; &nbsp; &nbsp; &nbsp;└── tyGSOctal
├── openssl
│&nbsp; &nbsp;└── openssl-1.1.1j
│&nbsp; &nbsp; &nbsp; &nbsp;├── bin
│&nbsp; &nbsp; &nbsp; &nbsp;├── include
│&nbsp; &nbsp; &nbsp; &nbsp;├── lib
│&nbsp; &nbsp; &nbsp; &nbsp;├── share
│&nbsp; &nbsp; &nbsp; &nbsp;└── ssl
├── openssl0
│&nbsp; &nbsp;└── openssl-1.1.1j
│&nbsp; &nbsp; &nbsp; &nbsp;├── apps
│&nbsp; &nbsp; &nbsp; &nbsp;├── Configurations
│&nbsp; &nbsp; &nbsp; &nbsp;├── crypto
│&nbsp; &nbsp; &nbsp; &nbsp;├── demos
│&nbsp; &nbsp; &nbsp; &nbsp;├── doc
│&nbsp; &nbsp; &nbsp; &nbsp;├── engines
│&nbsp; &nbsp; &nbsp; &nbsp;├── external
│&nbsp; &nbsp; &nbsp; &nbsp;├── fuzz
│&nbsp; &nbsp; &nbsp; &nbsp;├── include
│&nbsp; &nbsp; &nbsp; &nbsp;├── lib
│&nbsp; &nbsp; &nbsp; &nbsp;├── ms
│&nbsp; &nbsp; &nbsp; &nbsp;├── os-dep
│&nbsp; &nbsp; &nbsp; &nbsp;├── ssl
│&nbsp; &nbsp; &nbsp; &nbsp;├── test
│&nbsp; &nbsp; &nbsp; &nbsp;├── tools
│&nbsp; &nbsp; &nbsp; &nbsp;├── util
│&nbsp; &nbsp; &nbsp; &nbsp;└── VMS
├── rpcsvc
│&nbsp; &nbsp;└── rpcsvc-proto-1.4.2
│&nbsp; &nbsp; &nbsp; &nbsp;├── m4
│&nbsp; &nbsp; &nbsp; &nbsp;├── po
│&nbsp; &nbsp; &nbsp; &nbsp;├── rpcgen
│&nbsp; &nbsp; &nbsp; &nbsp;└── rpcsvc
├── streamdevice
│&nbsp; &nbsp;└── StreamDevice-master
│&nbsp; &nbsp; &nbsp; &nbsp;├── config
│&nbsp; &nbsp; &nbsp; &nbsp;├── configure
│&nbsp; &nbsp; &nbsp; &nbsp;├── dbd
│&nbsp; &nbsp; &nbsp; &nbsp;├── docs
│&nbsp; &nbsp; &nbsp; &nbsp;├── include
│&nbsp; &nbsp; &nbsp; &nbsp;├── pcre
│&nbsp; &nbsp; &nbsp; &nbsp;├── src
│&nbsp; &nbsp; &nbsp; &nbsp;└── streamApp
└── synApps
&nbsp; &nbsp; └── synApps_6_1
&nbsp; &nbsp; &nbsp; &nbsp; └── support


139 directories







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "paulscherrerinstitute/StreamDevice"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月1日(星期四) 晚上10:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [paulscherrerinstitute/StreamDevice] An error occurred while installing StreamDevice (#72)





 
It should work like this.
 Your StreamDevice installation is /home/lytt/epics/streamdevice/StreamDevice-master? (with for example /home/lytt/epics/streamdevice/StreamDevice-master/src/StreamCore.cc)
 You configured ASYN in /home/lytt/epics/streamdevice/StreamDevice-master/configure/RELEASE?
 Is there a directory /home/lytt/epics/streamdevice/configure ? That may be a problem.
 What do you have in /home/lytt/epics? If you have tree installed, can you run tree -d -L 3 -I 'O.*' in /home/lytt/epics and mail the result to me?

**Comment by dirk-zimoch** [comment]
I do not know why it does not work for you.
I can try to set up my own directory just as yours and see what happens. But not before next week.

**Comment by Lytt-2020** [comment]
Okay, thank you for your attention! If you have any results, please email me in time. Thank you very much!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "paulscherrerinstitute/StreamDevice"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月1日(星期四) 晚上10:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [paulscherrerinstitute/StreamDevice] An error occurred while installing StreamDevice (#72)





 
I do not know why it does not work for you.
 I can try to set up my own directory just as yours and see what happens. But not before next week.

**Comment by dirk-zimoch** [comment]
I have set up a system like yours and have absolutely no problem compiling everything.
I have `ASYN=/home/lytt/epics/asyn4/asyn4-38` in my `configure/RELEASE` as that is where you have asyn installed. (I also set `SUPPORT`, `CALC`, `PCRE` and `EPICS_BASE` but that's another story.)  I run `make` in `StreamDevice-master` and the include path shows up in the compiler arguments and StreamDevice has no problem finding `asynDriver.h`:
```
/usr/bin/g++  -D_GNU_SOURCE -D_DEFAULT_SOURCE      -D_X86_64_  -DUNIX  -Dlinux   -DUSE_TYPED_RSET
-DSTREAM_INTERNAL   -O3   -Wall    -m64 -fPIC -I. -I../O.Common -I. -I. -I.. -I../../include/compiler/gcc
-I../../include/os/Linux -I../../include      -I/home/lytt/epics/asyn4/asyn4-38/include
-I/usr/local/epics/base-7.0.5/include/compiler/gcc -I/usr/local/epics/base-7.0.5/include/os/Linux
-I/usr/local/epics/base-7.0.5/include        -MM -MF AsynDriverInterface.d  ../AsynDriverInterface.cc
```

 The only way I found to make asyn **not** show up in a `-I` option to the compiler as in your case is to spell the path wrong. If the path does not exist, then it will not show. Check again your `ASYN` setting.

**Comment by Lytt-2020** [comment]
Thanks for your attention! This problem has been solved. As you said, it was caused by a path editing error. Thanks again for your reply! Thank you! And wish you a happy life!






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "paulscherrerinstitute/StreamDevice"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月27日(星期二) 下午5:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [paulscherrerinstitute/StreamDevice] An error occurred while installing StreamDevice (#72)





 
I have set up a system like yours and have absolutely no problem compiling everything.
 I have ASYN=/home/lytt/epics/asyn4/asyn4-38 in my configure/RELEASE as that is where you have asyn installed. (I also set SUPPORT, CALC, PCRE and EPICS_BASE but that's another story.)  I run make in StreamDevice-master and the include path shows up in the compiler arguments and StreamDevice has no problem finding asynDriver.h:
 /usr/bin/g++  -D_GNU_SOURCE -D_DEFAULT_SOURCE      -D_X86_64_  -DUNIX  -Dlinux   -DUSE_TYPED_RSET -DSTREAM_INTERNAL   -O3   -Wall    -m64 -fPIC -I. -I../O.Common -I. -I. -I.. -I../../include/compiler/gcc -I../../include/os/Linux -I../../include      -I/home/lytt/epics/asyn4/asyn4-38/include -I/usr/local/epics/base-7.0.5/include/compiler/gcc -I/usr/local/epics/base-7.0.5/include/os/Linux -I/usr/local/epics/base-7.0.5/include        -MM -MF AsynDriverInterface.d  ../AsynDriverInterface.cc  
The only way I found to make asyn not show up in a -I option to the compiler as in your case is to spell the path wrong. If the path does not exist, then it will not show. Check again your ASYN setting.
