### ISSUE TITLE
Packaging as a standalone EPICS module

### ISSUE THREAD

**Issue by darcato** [paulscherrerinstitute/StreamDevice#9]
Is there a specific reason why this must be put inside the application top folder? All the other epics modules are distributed as standalone support library to be linked by the application.
Can this be done here? I know it can easily be done by the user, but this change would help to standardize the way a user installs an epics module.

**Comment by keenanlang** [comment]
>Can this be done here?

Late response, but the APS does have a packaging of streamDevice as a standard epics module.

https://github.com/epics-modules/stream

**Comment by darcato** [comment]
Thanks, I completely missed it. 
I will use that repository!

**Comment by dirk-zimoch** [comment]
I'm working on it. Version 2.8 will come as a standard epics module. At 
the moment I am still working so some other improvements...

Dirk

**Comment by dirk-zimoch** [comment]
Done in the current master branch.
