### ISSUE TITLE
No example IOC application after build

### ISSUE THREAD

**Issue by LeeYangLBLBCS** [paulscherrerinstitute/StreamDevice#92]
According to StreamDevice documentation here:
https://paulscherrerinstitute.github.io/StreamDevice/setup.html#lib
"This will create and install the stream library and the stream.dbd file and an example IOC application."

I didn't find the example IOC application, at least not under the usually directory name "iocs" similar to all other EPICS drivers.
Could it be hiding under a different name?

**Comment by dirk-zimoch** [comment]
I do not create an ioc directory. I have seen no need for that.
In the streamApp directory are a few example *.cmd scripts. They load stuff directly from the O.* directories.
Also the streamApp executable and streamApp.dbd are installed to bin and dbd, respectively.

**Comment by LeeYangLBLBCS** [comment]
thanks.
